language: cpp

sudo: required
dist: bionic
os: linux
compiler: gcc

install:
  - |
    wget http://kayari.org/gcc-latest/gcc-latest.deb && sudo dpkg -i gcc-latest.deb
    export PATH=/opt/gcc-latest/bin:$PATH
    export LD_RUN_PATH=/opt/gcc-latest/lib64
    git clone https://github.com/Microsoft/vcpkg.git
    cd vcpkg
    ./bootstrap-vcpkg.sh -disableMetrics
    ./vcpkg integrate install
    ./vcpkg install range-v3 fmt cairo harfbuzz freetype
    cd ..

before_script:
  - gcov --version
  - pip install --user cpp-coveralls

after_success:
  - coveralls --root . --include include --include src --include tests/unit_tests -E .*doctest\.v\..* --gcov-options '\-lp'

script:
  - |
    mkdir build
    cd build
    cmake ./.. -DENABLE_COVERAGE:BOOL=TRUE -DCMAKE_TOOLCHAIN_FILE=./../vcpkg/scripts/buildsystems/vcpkg.cmake
    cmake --build . -- -j2
    ./tests/unit_tests/unit_tests
    cd ..
