name: ci
on:
  pull_request:
  release:
    types: [published]
  push:
    branches:

jobs:
  Test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-22.04
          - macos-14
          - windows-2022
        compiler:
          - llvm
          - gcc
        CMAKE_GENERATOR:
          - "Ninja Multi-Config"
        CPACK_GENERATOR:
          - ZIP

        include:
          # Inject GCOV variable for gcc
          - compiler: gcc
            GCOV: gcov
          # Inject GCOV variable for llvm
          - compiler: llvm
            GCOV: "llvm-cov gcov"

          - os: windows-2022
            compiler: msvc
            CMAKE_GENERATOR: "Visual Studio 17 2022"

          - os: macos-14
            compiler: appleclang

          - os: macos-14
            compiler: llvm
            CONFIGURE_FLAGS: "-DCMAKE_CXX_FLAGS=\"-stdlib=libc++ -I/Users/runner/llvm/include\" -DCMAKE_EXE_LINKER_FLAGS=\"-L/Users/runner/llvm/lib\" -CMAKE_MACOSX_RPATH=1 -DCMAKE_BUILD_RPATH=/Users/runner/llvm/lib"

        exclude:
          - os: macos-14
            compiler: gcc

          - os: windows-2022
            compiler: gcc

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/vcpkg
            ./build/vcpkg_installed
            ${{ env.CONAN_USER_HOME }}
            ~/.cache/pip
            ${{ env.HOME }}/.cache/vcpkg/archives
            ${{ env.XDG_CACHE_HOME }}/vcpkg/archives
            ${{ env.LOCALAPPDATA }}\vcpkg\archives
            ${{ env.APPDATA }}\vcpkg\archives
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ hashFiles('./vcpkg.json')}}-${{ matrix.CMAKE_GENERATOR }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.compiler }}-${{ hashFiles('./vcpkg.json') }}-

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}

          cmake: "3.28.4"
          ninja: true
          vcpkg: true
          ccache: true
          clangtidy: true
          task: true

          cppcheck: true

          gcovr: 7.2
          opencppcoverage: true

      - name: Initialize CodeQL
        if: ${{ contains(matrix.os, 'ubuntu') && contains(matrix.compiler, 'llvm') }}
        uses: github/codeql-action/init@v3
        with:
          languages: "cpp"

      - name: Test/Coverage
        run: |
          task coverage
        env:
          CMAKE_GENERATOR: ${{matrix.CMAKE_GENERATOR}}
          GCOV: ${{matrix.GCOV}}
          CONFIGURE_FLAGS: ${{matrix.CONFIGURE_FLAGS}}

      - name: Test release
        run: |
          task test_release
        env:
          CMAKE_GENERATOR: ${{matrix.CMAKE_GENERATOR}}
          GCOV: ${{matrix.GCOV}}
          CONFIGURE_FLAGS: ${{matrix.CONFIGURE_FLAGS}}

      - name: Install
        run: |
          task install
        env:
          CMAKE_GENERATOR: ${{matrix.CMAKE_GENERATOR}}
          CPACK_GENERATOR: ${{matrix.CPACK_GENERATOR}}

      - name: Perform CodeQL Analysis
        if: ${{ contains(matrix.os, 'ubuntu') && contains(matrix.compiler, 'llvm') }}
        uses: github/codeql-action/analyze@v3

      - name: Publish Tagged Release
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.CPACK_GENERATOR != '' }}
        with:
          files: |
            build/*-*Release*-*.*

      - name: Publish to codecov
        uses: codecov/codecov-action@v4
        with:
          flags: ${{ runner.os }}
          name: ${{ runner.os }}-coverage
          files: ./build/coverage.xml