name: macos
on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          brew install automake pkg-config
          vcpkg update
          vcpkg install expat range-v3 fmt cairo harfbuzz freetype doctest
      - name: build & test
        run: |
          cd ../mfl
          mkdir build
          cd build
          cmake ./.. -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . -- -j2
          ./tests/unit_tests/unit_tests
