name: ubuntu
on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: update gcc
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -q
          sudo apt-get install autopoint gperf gcc-10 g++-10 -y
      - name: install dependencies
        run: |
          export CXX="g++-10" CC="gcc-10"
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh -disableMetrics
          ./vcpkg integrate install
          sed -i 's/"${CURRENT_PACKAGES_DIR}\/debug\/etc")/"${CURRENT_PACKAGES_DIR}\/debug\/etc")\nfile(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}\/share\/fontconfig\/locale")/' ./ports/fontconfig/portfile.cmake
          ./vcpkg install libuuid expat range-v3 fmt cairo harfbuzz freetype doctest
      - name: build & test
        run: |
          cd ../mfl
          mkdir build
          cd build
          cmake ./.. -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_TOOLCHAIN_FILE=./../vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . -- -j2
          ./tests/unit_tests/unit_tests