name: windows
on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          cd ..
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          .\vcpkg.exe install expat range-v3 fmt cairo harfbuzz freetype doctest --triplet x64-windows
      - name: build & test
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\..\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_CXX_FLAGS="/permissive- /std:c++latest /Zc:__cplusplus /utf-8 /EHsc /DNOMINMAX" ./..
          cmake --build . --config "Release"
          .\tests\unit_tests\Release\unit_tests.exe